### ISSUE TITLE
Issue with non-standard evaluation

### ISSUE THREAD

**Issue by dahtah** [sgsokol/Deriv#10]
Dear Serguei, 

Thanks for writing this package, it's very useful. There's a bug related to non-standard evaluation that prevents Deriv from being used inside of a function: 

```
library(Deriv)
g = function(f) Deriv(f)
g(cos)
```

I'm trying to use Deriv to write a function that automatically produces Taylor approximations, but that requires passing a function as argument. Any ideas on how to fix this? 

Thanks

Simon

**Comment by sgsokol** [comment]
Dear Simon,

Thanks for your interest to the package.
Unfortunately, I don't know a way to retrieve an original name of a primitive function like cos(x) once it was assigned to another variable (here a parameter f in function g).
Instead, would it be possible for you to consider other call forms like g(~cos(x)) or g(quote(cos(x)) or g("cos(x)")?

Best,
Serguei.

**Comment by sgsokol** [comment]
Dear Simon,

Finally, I have managed to figure out a way to get a true name of renamed primitive function.
The fix is in actual devel branch. Now, your example should work.
This feature will be integrated in the next 3.8.1 release.

Best,
Sergueï.
