### ISSUE TITLE
Incorrect derivatives?

### ISSUE THREAD

**Issue by cwliu007** [sgsokol/Deriv#12]
Hi Serguei,

I have an example that Deriv may not be able to get correct answer. See
~~~
P <- function(x,Theta){	
	xi_rho1 = exp( x[3] )
	sumTD = x[2]*(Theta-x[1])
	xi_td1 = exp(abs(sumTD))
	q1 = xi_td1/(xi_rho1 + xi_td1)
	p1 = xi_rho1/(xi_rho1 + xi_td1)
	
	xi_rho1 = exp( x[6] )
	sumTD = x[5]*(Theta-x[4])
	xi_td1 = exp(abs(sumTD))
	q1b = xi_td1/(xi_rho1 + xi_td1)
	p1b = xi_rho1/(xi_rho1 + xi_td1)
	
	p = 1/(1+ (q1*p1b)/(p1*q1b) )
	cbind(p,1 - p)				
}
require("Deriv")
dp1 = Deriv(P,c(x=1,x=2, x=3, x=4 ,x=5,x=6))
dp1(c(0,1,1,0,1,1), t(matrix(c(1))) )

# compared to
myenv <- new.env()
assign("rho", c(0,1,1,0,1,1), envir = myenv)
assign("theta", t(matrix(c(1))) , envir = myenv)
numericDeriv(quote(P(rho,theta)), c("rho", "theta"), myenv)
~~~

**Comment by cwliu007** [comment]
Ah... I found the problem. I should not reuse the same name in the function (i.e., xi_rho1, sumTD, and xi_td1). Sorry for inconvenience.

**Comment by sgsokol** [comment]
Hi genwei,

I have tried to fix it. It works on my side. Could you please run your test by installing the current dev version?
devtools:install_github("sgsokol/Deriv", ref="devel")

**Comment by cwliu007** [comment]
Thanks for the update (I noted that `devtools:` should be `devtools::`). But I found still a little bug for other examples:

```
dp1(c(-1,2,2,1,1,1), 1 )
# compared to
assign("rho", c(-1,2,2,1,1,1), envir = myenv)
numericDeriv(quote(P(rho,theta)), c("rho", "theta"), myenv)
```

`x_41` and `x_42` were not correct.

**Comment by sgsokol** [comment]
at the chosen point the function is not differentiable because of abs(). So both the values of dp1() and numDeriv() are false. You can modify corresponding drule entries to return explicitly NA at such points: drule[["abs"]] <- alist(x=ifelse(x==0, NA, sign(x)))
drule[["sign"]] <- alist(x=ifelse(x==0, NA, 0))
Would it help?

**Comment by cwliu007** [comment]
Yes. Thank you so much for the help:)
