### ISSUE TITLE
incorporating custom drules in a downstream package

### ISSUE THREAD

**Issue by bbolker** [sgsokol/Deriv#13]
(Don't know if this is the right venue. If not, just close this and I'll post it somewhere else (r-devel mailing list or StackOverflow ...)

I'm developing a package (with @parksw3 on github), https://github.com/bbolker/fitsir , that uses `Deriv` with some custom values in `drule`.  We're having trouble figuring out how to export our custom `drule` values so that they work when our package is loaded.

We made a stripped-down version of the package [here](https://github.com/parksw3/Derivtest).  There is a `broken` branch, which we initially thought would work but doesn't, and a `master` branch, which works but seems clunky to us.

Here's an example from an interactive session:
```
library(Deriv)
myfun <- function(x, y) x + y
mydfun <- function(x, y) NULL
drule[["myfun"]] <- alist(x=mydfun(x, x), y=mydfun(y, y))
Deriv(myfun(x, y), c("x", "y"))
## result:
## c(x = mydfun(x, x), y = mydfun(y, y))
```

In the `broken` branch, we put these definitions in our  R package code.  We export all of the functions in the package: *even if we export the `drule` function*, we get the following:

```
library(Derivtest)
myderiv ## computed within package: as in interactive session
## c(x = mydfun(x, x), y = mydfun(y, y))
Deriv(myfun(x, y), c("x", "y"))
## x=1, y=1
Deriv2(myfun(x, y), c("x", "y"))
## x=0, y=0
```

What seems odd is that `find("drule")` finds a copy of `drule` in the `Derivtest` environment (before the copy in `Deriv`, which has our custom `drule` in it. We can get this to work (`master` branch) if we add our new `drule` on the fly, within the function:

```
Deriv2 <- function(expr, var) {
    drule[["myfun"]] <- alist(x=mydfun(x, x), y=mydfun(y, y))
    Deriv(substitute(expr), var)
}
```

We've tried a lot of different solutions (assigning to global environment, playing around with the `env` argument), but haven't been able to figure out a better solution.

Suggestions?

**Comment by sgsokol** [comment]
Le 09/06/2017 à 15:40, Ben Bolker a écrit :
>
> (Don't know if this is the right venue. If not, just close this and I'll post it somewhere else (r-devel mailing list or StackOverflow ...)
>
You are in right place here as far as Deriv is concerned.

> I'm developing a package (with @parksw3 <https://github.com/parksw3> on github), https://github.com/bbolker/fitsir , that uses |Deriv| with some custom values 
> in |drule|. We're having trouble figuring out how to export our custom |drule| values so that they work when our package is loaded.
>
> We made a stripped-down version of the package here <https://github.com/parksw3/Derivtest>. There is a |broken| branch, which we initially thought would work 
> but doesn't, and a |master| branch, which works but seems clunky to us.
>
> Here's an example from an interactive session:
>
> |library(Deriv) myfun <- function(x, y) x + y mydfun <- function(x, y) NULL drule[["myfun"]] <- alist(x=mydfun(x, x), y=mydfun(y, y)) Deriv(myfun(x, y), c("x", 
> "y")) ## result: ## c(x = mydfun(x, x), y = mydfun(y, y)) |
>
> In the |broken| branch, we put these definitions in our R package code. We export all of the functions in the package: /even if we export the |drule| 
> function/, we get the following:
>
> |library(Derivtest) myderiv ## computed within package: as in interactive session ## c(x = mydfun(x, x), y = mydfun(y, y)) Deriv(myfun(x, y), c("x", "y")) ## 
> x=1, y=1 Deriv2(myfun(x, y), c("x", "y")) ## x=0, y=0|
|The problem here (in broken branch) is that your customized drule is available only
during library(Derivtest) call. Just after it, it is reset to its initial value,
i.e. the entry ||drule[["myfun"]]| is simply NULL.

> ||
>
> What seems odd is that |find("drule")| finds a copy of |drule| in the |Derivtest| environment (before the copy in |Deriv|, which has our custom |drule| in it. 
> We can get this to work (|master| branch) if we add our new |drule| on the fly, within the function:
>
> |Deriv2 <- function(expr, var) { drule[["myfun"]] <- alist(x=mydfun(x, x), y=mydfun(y, y)) Deriv(substitute(expr), var) } |
>
> We've tried a lot of different solutions (assigning to global environment, playing around with the |env| argument), but haven't been able to figure out a 
> better solution.
>
> Suggestions?
>
What about to make your drule definitions in .onload() function?
This supposes that your don't modify drule in the package code (like
in broken branch) otherwise the definitions made in .onload() will be
lost too. Be aware that with .onload() trick, the variables myderiv
of the master branch will have bad values as a new drule is not yet available
during library(Derivtest) call (it will be at the end of it). So instead of myderiv
you may want to define smth like

    fmyderiv <- function() Deriv(myfun(x, y), c("x", "y"))

then the following should work:

    library(Derivtest) # .onload() will update drule
    fmyderiv()
    # c(x = mydfun(x, x), y = mydfun(y, y))
    drule[["myfun"]]
    # $x
    # mydfun(x, x)
    #
    # $y
    # mydfun(y, y)
If you don't manage to reproduce this result, I can propose a patch for Derivtest.

Does it help?

**Comment by bbolker** [comment]
thanks, this is very useful!
