### ISSUE TITLE
Things like c(x, y) ^ 2 are not supported

### ISSUE THREAD

**Issue by Non-Contradiction** [sgsokol/Deriv#15]
Dear Serguei, thank you very much for making Deriv and quick response! I met another problem in using Deriv.
```
> f <- function(x, y){
+     c(x ^ 2, y ^ 2)
+ }
> Deriv(f)
function (x, y) 
c(x = c(2 * x, 0), y = c(0, 2 * y))
> f <- function(x, y){
+     c(x, y) ^ 2
+ }
> Deriv(f)
Error in !ize 
> 
```
So things like `c(x^2, y^2)` are supported, and things like `c(x, y)^2` are not. Is `Deriv` going to support this?

**Comment by sgsokol** [comment]
Thank you to spend your time on it. Hoping Deriv will get better than ever with your reports.
This bug is corrected in 3.8.3 but with CRAN updating policy, the package cannot be resubmitted before one month at least. So use github version if needed.

**Comment by Non-Contradiction** [comment]
Things work as expected! Thanks very much! If I do something like `xy <- c(x,y)`, R will give me some warnings that the length of conditions are larger than 0, results here are correct.
```
> f <- function(x,y){
+     xy <- c(x,y) 
+     xy ^ 2
+ }
> Deriv(f)
function (x, y) 
{
    .e1 <- c(x, y)
    c(x = c(2, 0) * .e1, y = c(0, 2) * .e1)
}
Warning messages:
1: In if (de_a == 0) { : Length of condition greater than 1
2: In if (de_a == 0) { : Length of condition greater than 1
```

**Comment by sgsokol** [comment]
Right. It was annoying and unnecessary warning. It is fixed now.
