### ISSUE TITLE
feature request: make it possible to extend Deriv by defining primitives

### ISSUE THREAD

**Issue by chuanwen** [sgsokol/Deriv#16]
In the python package [autograd](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md), user can definite their own primitives.

Right now one can do something similar in Deriv package, like below
```
library(Deriv)
logsumexp <- function(x) {
   max_x = max(x)
   log(sum(exp(x-max_x))) + max_x
}

df_logsumexp <- function(x) {
  e_x = exp(x - max(x))
  e_x/sum(e_x)
}

drule[["logsumexp"]] = alist(x=df_logsumexp(x))

df <- Deriv(logsumexp)
df(c(1,2))

[1] 0.2689414 0.7310586

```
But above approach is hidden away from users (I only know this after I checked the R source code).

**Comment by sgsokol** [comment]
Hidden? Really? What about to "read this fine manual"?
`?Deriv ` says
```
• It's easy to add custom entries to the derivatives table, e.g.
  ‘drule[["cos"]] <- alist(x=-sin(x))’"
```
and later on
```
To add your own derivative rule for
 a function called say ‘sinpi(x)’ calculating sin(pi*x), do
 ‘drule[["sinpi"]] <- alist(x=pi*cospi(x))’.
```
There is also an example of custom rule for `abs(x)` to make appear NA at singularity.

**Comment by chuanwen** [comment]
Sorry, I made the mistaken of spending too little time on reading the rdoc -- I only quickly scanned the github page and read the first few lines of the ?Deriv

**Comment by sgsokol** [comment]
Well, I'll mention it in Readme too.
Thanks.
