### ISSUE TITLE
Does not work for list of functions (?)

### ISSUE THREAD

**Issue by savemark** [sgsokol/Deriv#17]
```R
funlist <- function(par) {f <- function(x) x^par; return(list(f = f))}
myfun <- funlist(2) # x^2

# is.function(myfun$f)
# [1] TRUE

# myfun$f
# function(x) x^par
# <environment: 0x000000002e1b72b8>

Deriv(myfun$f)
Error in get(stch, mode = "function", envir = env) : 
  object 'myfun$f' of mode 'function' was not found
```

**Comment by savemark** [comment]
Nevermind, I did find a solution:
```R
list2env(myfun, environment())
Deriv(f)
#function (x) 
#par * x^(par - 1)
```
 
I'll leave it here in case anyone else have the same problem.

**Comment by sgsokol** [comment]
Right. As the error message suggests, `get()` cannot use expression with `$` or any subindexing to find an object. It must be a plain name like `f` in your second example.

**Comment by sgsokol** [comment]
After some reflexion, I have found a way to circumvent `get()` limitations and now (i.e. starting from v3.8.4) your example gives:
```
(fd<-Deriv(myfun$f))
# function (x) 
# par * x^(par - 1)
# <environment: 0x29034b8>
fd(3)
# [1] 6
```
Please feel free to report any problem with proposed solution.

PS. The version 3.8.4 is not on CRAN yet (as of this writing) but you can test it with usual
```
devtools::install_github("sgsokol/Deriv")
```
