### ISSUE TITLE
Can't simplify `y + c(1, 2)`

### ISSUE THREAD

**Issue by notEvil** [sgsokol/Deriv#18]
If you run `Deriv::Simplify(quote(y + c(1, 2)))` it will fail due to `as.character` returning a vector with length 2 at Simplify.R:146. If replaced by `toString`, it works. I'm not sure if `toString` is the correct fix for this issue though ^^

**Comment by sgsokol** [comment]
Well done. It is fixed to `format1()` as used elsewhere in the package.
