### ISSUE TITLE
Simplify `y + c(0, 1)` fails

### ISSUE THREAD

**Issue by notEvil** [sgsokol/Deriv#19]
`Deriv::Simplify(quote(y + c(0, 1)))` returns `y` because of `b == 0` in Simplify.R:133 (and maybe 130 too). It will only consider the first value which turns out true in this case. Replacing the expression with `identical(b, 0)` (and `identical(a, 0)` on line 130) fixed the issue.

**Comment by sgsokol** [comment]
Thanks. The `identical()` tirck was already used in the package but not in systematic way as underlined by this bug.

**Comment by sgsokol** [comment]
Finally, `identical()` is not good enough because of
```
a=0
identical(a, 0L)
#[1] FALSE
```
We will use an ad hoc function `is.numconst(a, 0)`
