### ISSUE TITLE
browser()

### ISSUE THREAD

**Issue by koenvanbenthem** [sgsokol/Deriv#23]
The current cran version has a browser() command left uncommented on line 456 of the file Deriv.R.

**Comment by sgsokol** [comment]
Thanks. It is already corrected in the devel branch. Will be on CRAN with the next release.
Meanwhile, you can install the devel version with `devtools::install_github("sgsokol/Deriv", "devel")`

**Comment by koenvanbenthem** [comment]
Thank you very much for the quick reply!
