### ISSUE TITLE
Error about the derivative for product

### ISSUE THREAD

**Issue by Rednose22** [sgsokol/Deriv#24]
When I try to calculate the partial derivative of below function, there's an error caused as attached.
![image](https://user-images.githubusercontent.com/69974660/115456531-2a27cc00-a21b-11eb-8059-c59bcdcebce7.png)

The code is as below:
func.2 <- function(thta) log(prod(1.5*thta*(x[i]^0.5)*exp(-thta*(x[i]^1.5)), i=1, n))
Deriv(func.2, "thta")

**Comment by sgsokol** [comment]
That's normal. `prod()` function is not in the derivative rule table of Deriv. But given that you take a log of prod you can try to replace it with a sum of logs. Remember that Deriv is supposed to differentiate by a scalar variable, so some side effects can appear with sum(). See examples in Deriv help page.
Moreover, your syntax `prod(..., i=1,n)` is not a correct R syntax. You should also read the help page of prod().

**Comment by Rednose22** [comment]
Thanks.
