### ISSUE TITLE
Bug using long expressions in Deriv() related to deparse()

### ISSUE THREAD

**Issue by philschus** [sgsokol/Deriv#26]
There seems to be an issue when using a long expression as f-argument in Deriv().

For example:

> Deriv(function(x) ee*ddddddddddddd*log(x)^(1-sig)*exp(x)*h, "x")

results in the following error "Error in drule[[fch]] : wrong arguments for subsetting an environment", while the one character shorter 

> Deriv(function(x) ee*dddddddddddd*log(x)^(1-sig)*exp(x)*h, "x")

works fine. The problem seems to be related to deparsing f [in particular line 262 in Deriv.R: fch <- deparse(substitute(f))]. The issue is that if the argument is too long deparse() splits its output and returns a vector of strings instead of returning a single string. Using deparse1() which wraps deparse() and uses a paste(... , collapse = " ") call on top should fix that issue.

By the way: Defining the function first, e.g. 

> myfun <- function(x) ee*ddddddddddddd*log(x)^(1-sig)*exp(x)*h
> Deriv(myfun, "x")

obviously works fine.

**Comment by sgsokol** [comment]
Thanks for reporting and correcting.
The fix is included in v4.1.5. It will be submitted to CRAN in some future, meanwhile this new version is installable from GitHub via devtools::install_github().
