### ISSUE TITLE
Error in missing(FALSE) : invalid use of 'missing'

### ISSUE THREAD

**Issue by FischerJoBio** [sgsokol/Deriv#27]
Hi,

I have a problem with applying the Deriv function to a custom R function I defined. Here is a MWE (forget about whether it does something useful or not) that throws the error for me:

> f_test <- function (x,y) norm(acos(x%*%y), type="2")
> Deriv(f_test, "x")
> Error in missing(FALSE) : invalid use of 'missing'

It might be that this error is caused by something related to acos (auto-completion of missing arguments maybe?), a doublecheck for the simplest function I could come up with works, so it's not necessarily the installation:

> f_test <- function (x,y) {x%*% y}
> Deriv(f_test, "x")
> function (x, y) 
> y

My R version is 4.2.0 for macOS, the installed Deriv package version is 4.1.3

**Comment by sgsokol** [comment]
Thanks for reporting. I confirm the error and will see what can be done.

**Comment by sgsokol** [comment]
I have one bad news and one possibly good.
The bad news is that 'norm()' function used in your example won't be able differentiated by Deriv for several reasons:
 - it uses 'svd()' whose body is rewritten with actual and default arguments including LINPACK=FALSE. It leads to replace expression like 'missing(LINPACK)' by 'missing(FALSE)' which is a non sense. Unfortunately, Deriv already relies heavily on use of the default arguments in other functions and it cannot be reverted;
 - still in 'svd()', a variable 'x' is redefined which can give another non sense where expression like 'x=as.matrix(x)' becomes 'acos(x%y)=as.matrix(acos(x%y))';
 - finally, 'La.svd()' which does the real job in 'svd()', calls '.Internal()' which excludes any hope for automatic differentiation.

Now, if you redefine a call to 'norm(x, type="2")' with a custom function
```
norm2=function(x) sqrt(sum(x*x))
```
then may be you can get something making sense:
```
> f_test2 <- function (x,y) norm2(acos(x%*%y))
> Deriv(f_test2, "x")
function (x, y) 
{
    .e1 <- x %*% y
    .e2 <- acos(.e1)
    0.5 * (sum(-(2 * (y * .e2/sqrt(1 - .e1^2))))/sqrt(sum(.e2^2)))
}
```

**Comment by FischerJoBio** [comment]
Thank you for your help, this fixes it!

**Comment by sgsokol** [comment]
> Thank you for your help, this fixes it!

May be not completely. Please pay particular attention to NB3 in ?Deriv which warns about side effects related to vector lengths. So check that in your case, Deriv result corresponds to expected length and value.
