### ISSUE TITLE
Deriv outputs not vectorizing as I expected

### ISSUE THREAD

**Issue by stephenjewson** [sgsokol/Deriv#28]
I love Deriv. It's amazing.
But I discovered an interesting feature, that caught me out.
Short story: the derivatives don't vectorize in the way I expected. 
I can illustrate that with two examples.

test 1 (works as I expected it would):

    f=function(x,y) x^2+y^2
    fd=Deriv(f) 
    x=c(1,2,3)
    y=c(1,2,3)
    fd(x,y)

test 2 (doesn't work as I expected it would):

    f=function(x) x^2+y #the only difference is that y^2 has become y
    fd=Deriv(f)
    x=c(1,2,3)
    y=c(1,2,3)
    fd(x,y)

In the second case, the derivative function fd doesn't vectorize in the way I expected it would.
Because the derivative doesn't depend on y, it doesn't vectorize over y.
As a result, the output vector is not the shape I expected. 
I expected a vector with 6 elements (two derivatives, each at 3 values of x,y) but I only got a vector with 4 elements.

My conclusion is that I shouldn't expect the derivative functions to vectorize.

**Comment by savemark** [comment]
If you add Vectorize to the code, as you mention, it works as one expects it to, but I'm not sure if this is intended or not.

```
f=function(x, y) x^2+y #the only difference is that y^2 has become y
fd=Deriv(f)
x=c(1,2,3)
y=c(1,2,3)
vfd <- Vectorize(fd)
vfd(x,y)
```

 [,1] [,2] [,3]
x    2    4    6
y    1    1    1

**Comment by stephenjewson** [comment]
Thankyou.

**Comment by stephenjewson** [comment]
There's a funny thing about Vectorize, though. 

It vectorizes the code, and then it adds an extra line at the end, that looks like this:
    <environment: 0x000001df9503a648>

When I "source" the code, that extra line gives an error.

Any idea how to remove that line?

**Comment by sgsokol** [comment]
This is a frequent not a question but a "deception" for Deriv which is written for scalar differentiation in mind but often happens to work also for vector arguments. This happens so frequently that people consider it as an error when vector expressions are not properly treated. Please see NB3 in `?Deriv::Deriv` for some considerations that could be helpful in such cases.

**Comment by sgsokol** [comment]
```
> f=function(x,y) x^2+y #the only difference is that y^2 has become y
> fd=Deriv(f, combine="cbind")
> x=c(1,2,3)
> y=c(1,2,3)
> fd(x,y)
     x y
[1,] 2 1
[2,] 4 1
[3,] 6 1
```
