### ISSUE TITLE
R CMD check example using Deriv fails

### ISSUE THREAD

**Issue by notEvil** [sgsokol/Deriv#4]
When I use the following code as a package example

```
f = quote( (1 + alpha)^(1/alpha) )
d1 = Deriv::Deriv(f, 'alpha')
print(d1)
d2 = Deriv::Deriv(d1, 'alpha')
print(d2)
```

and run `R CMD check` I get the following error

```
Error in expr[[3]][[2]] : object of type 'symbol' is not subsettable
Calls: <Anonymous> ... Simplify -> Simplify_ -> Simplify.rule -> Numden -> Numden
```

at `d2 = ...`. The first derivative works just as expected. What's wrong? Did I miss something crucial there?

**Comment by sgsokol** [comment]
It was a bug in power simplification procedures.
Could you try v3.5.3 pls?
devtools::install_github("sgsokol/Deriv", ref="v3.5.3")

**Comment by notEvil** [comment]
wow, that was amazingly fast. and the error is gone now :)
