### ISSUE TITLE
problem with composite function

### ISSUE THREAD

**Issue by ghost** [sgsokol/Deriv#6]
Hi,

Thanks for the package. I am using version 

```
Package: Deriv
Type: Package
Title: Symbolic Differentiation
Version: 3.5.6
Date: 2015-09-23
Authors@R: c(person(given="Andrew", family="Clausen", role="aut"), person(given="Serguei",
          family="Sokol", role=c("aut", "cre"), email="sokol@insa-toulouse.fr"))
Description: R-based solution for symbolic differentiation. It admits user-defined
          function as well as function substitution in arguments of functions to be
          differentiated. Some symbolic simplification is part of the work.
License: GPL (>= 3)
Suggests: testthat
BugReports: https://github.com/sgsokol/Deriv/issues
NeedsCompilation: no
Packaged: 2015-09-24 13:50:15 UTC; sokol
Author: Andrew Clausen [aut], Serguei Sokol [aut, cre]
Maintainer: Serguei Sokol <sokol@insa-toulouse.fr>
Repository: CRAN
Date/Publication: 2015-09-25 00:43:31
Built: R 3.2.2; ; 2015-10-26 06:31:56 UTC; unix
```

 I used in a computation and run into a problem when the function to be differentiated contains a call to another function in which body there are more than one expression.
Here is a simple example

```
f<-function(x){ t<-x^2; log(t) }
g<-function(x) cos(f(x))
Deriv(g,"x")
```

returns the function

```
function (x) 
-(sin(f(x)) * {
    t <- x^2
    .t_x <- .t_x
    .t_x/t
})
```

Here `t_x` is not defined. I guess that this is somehow the result of some simplification step, but I could not really follow what `Deriv` does during the debugging. At some stage the expected code 

```
dargs
$x
{
    t <- x^2
    .t_x <- 2 * x
    .t_x/t
}
```

was in the `dargs` variable within `Deriv_`.

During the differentiation of a more complicated function it happened that the variable .e1 was used before a value was assigned to it, and also many assignment of the type `.esomething <- .esomething` (the left hand side and the right hand side are the same) I do not know whether these issues are related.

Thanks
Vilmos Prokaj

**Comment by sgsokol** [comment]
Thanks for this bug report.
The problem was an over-simplification.
Could you give a ride to the fixed version in the devel branch on github? (devtools::install_github("sgsokol/Deriv", ref="devel"))

**Comment by ghost** [comment]
Thanks .
It seems to work now.
Viilmos Prokaj

**Comment by sgsokol** [comment]
Submitted to CRAN as v3.6.0
