### ISSUE TITLE
Error in FUN(X[[i]], ...) : Could not retrieve body of '[()'

### ISSUE THREAD

**Issue by cwliu007** [sgsokol/Deriv#8]
Hi Deriv authors,

I have a testing example that ran into problem:

```
    fun <- function(t,g,tau) c(1/(1+exp(t-g - tau[2])),1/(1+exp(-(t-g - tau[1]))) )
    require("Deriv")
    dp1 = Deriv(fun,c("t"))
```

How to solve this?

**Comment by sgsokol** [comment]
Hi,
If it is not critical for you, you could rewrite your function as
|fun <- function(t,g,tau1, tau2) c(1/(1+exp(t-g - tau2)),1/(1+exp(-(t-g 
- tau1))) )

Does it help?
|||
Genwei007 has written at  Sun, 14 Feb 2016 01:00:45 -0800

**Comment by cwliu007** [comment]
Thanks. But I would like to keep tau as vector, because it may vary with the values of data.

**Comment by sgsokol** [comment]
The issue is fixed in the current version on githug (future v3.6.2). You can try it with devtools::install_github("sgsokol/Deriv")

**Comment by cwliu007** [comment]
Thank you! Now, it works for me.

**Comment by cwliu007** [comment]
Hi,

I tried the following this morning, but it didn't work:

```
    require("Deriv")
    fun <- function(t,g,tau,point){
        nu = c(1, exp(t-g[1]-tau[1]), exp(2*(t-g[2])-sum(tau[1:2])), exp(3*(t-g[3])-sum(tau[1:3])), exp(4*(t-g[4])-sum(tau[1:4])), exp(5*(t-g[5])-sum(tau[1:5])) )
        nus = nu[1:point]
        de = sum(nus)
        nus/de
    }
    dp1 = Deriv(fun,c("t"))
    dp2 = Deriv(dp1,c("t"))
```

It returns 0 for dp1 and dp2. I think `nu[1:point]` may be the crux.

**Comment by sgsokol** [comment]
Hi,

Le 15/02/2016 06:30, genwei007 a écrit :

> Hi,
> 
> I tried the following this morning, but it didn't work:
> 
> |require("Deriv") fun <- function(t,g,tau,point){ nu = c(1, exp(t-g[1]-tau[1]), exp(2_(t-g[2])-sum(tau[1:2])), exp(3_(t-g[3])-sum(tau[1:3])), 
> exp(4_(t-g[4])-sum(tau[1:4])), exp(5_(t-g[5])-sum(tau[1:5])) ) nus = nu[1:point] de = sum(nus) nus/de } dp1 = Deriv(fun,c("t")) dp2 = Deriv(dp1,c("t")) |
> 
> It returns 0 for dp1 and dp2. I think |nu[1:point]| may be the crux.
> 
> It could never work for symbolic derivation in this form.
> npoint is a run-time argument while for code derivation we
> would have to know its value at compilation time. (And even
> this is not yet implemented)

A close example (for a full npoint) can work:

```
    fun <- function(t,g,tau){
        nu = c(1, exp(t-g[1]-tau[1]), exp(2*(t-g[2])-sum(tau[1:2])), exp(3*(t-g[3])-sum(tau[1:3])), exp(4*(t-g[4])-sum(tau[1:4])), exp(5*(t-g[5])-sum(tau[1:5])) )
        nu/sum(nu)
    }
```

You could write similar functions for different values of npoint and call them depending on the value of npoint at 
run-time.
Best, Serguei.

**Comment by cwliu007** [comment]
Thanks for the tip:) Could we derive gradients for vectors? I do this because other R function requires vectorization. As following example:

```
    require("Deriv")
    fun <- function(x,Theta,ncat){
        nu <- c(1, exp(Theta - x[1]), exp(2*(Theta) - sum(x[1:2])) )
        nu/sum(nu)
    }       
    dp1 = Deriv(fun,c("x"))
    dp2 = Deriv(dp1,c("x"))
```

Warning message:
In if (de_a == 0) { :
  the condition has length > 1 and only the first element will be used

**Comment by sgsokol** [comment]
Genwei007 has written at  Sat, 20 Feb 2016 07:12:14 -0800

> Thanks for the tip:) Could we derive gradients for vectors? I do this 
> because other R function requires vectorization. As following example:
> 
> |require("Deriv") fun <- function(x,Theta,ncat){ nu <- c(1, exp(Theta - 
> x[1]), exp(2*(Theta) - sum(x[1:2])) ) nu/sum(nu) } dp1 = 
> Deriv(fun,c("x")) dp2 = Deriv(dp1,c("x")) |
> 
> Warning message:
> In if (de_a == 0) { :
> the condition has length > 1 and only the first element will be used
> 
> Yes, you can. You have to replace sum(x[1:2]) by x[1]+x[2] and call as
> dp1=Deriv(fun, c(x=1, x=2)); dp2=Deriv(dp1, c(x=1, x=2))

Best,
Serguei

**Comment by genwei007** [comment]
Hi Serguei,

Apologize to bother again!  What if `Theta` is vector?
~~~
	funLog <- function(x,Theta,ncat){
		nu <- cbind(1, exp(Theta - x[1] ), exp(2*(Theta) - (x[1]+x[2]) ) ) 
		de = nu[,1] + nu[,2] + nu[,3]
		p1 = nu[,1]/de
		p2 = nu[,2]/de
		p3 = nu[,3]/de
		log(cbind(p1,p2,p3))
	}	
	dp1 = Deriv(funLog,c(x=1,x=2))
~~~
BTW, `for (){}` and `rowSums` seems not working in Deriv for now. Does it mean I have to make formula as explicitly as possible, right? 

Thanks a lot!
CW

**Comment by cwliu007** [comment]
Hi Serguei,

Apologize to bother you again! How much does Deriv support for vectorized input and output? 

```
    funLog <- function(x,Theta,ncat){
        nu <- cbind(1, exp(Theta - x[1] ), exp(2*(Theta) - (x[1]+x[2]) ) ) # Theta is a matrix of [61,1]
        qua = 1:61
        de = nu[qua,1] + nu[qua,2] + nu[qua,3]
        p1 = nu[qua,1]/de
        p2 = nu[qua,2]/de
        p3 = nu[qua,3]/de
        cbind(p1,p2,p3)  
    }   
    dp1 = Deriv(funLog,c(x=1,x=2))
```

Error in Deriv_(a[[3]], x[ix], env, use.D, dsym, scache) : 
  Could not retrieve body of ':()'

Many thanks!

**Comment by sgsokol** [comment]
Hi,

I suggest to rewrite your function as
funLog <- function(x,Theta,ncat){
    nu1=1
    nu2=exp(Theta - x[1] )
    nu3=exp(2*(Theta) - (x[1]+x[2]) )
    de=nu1+nu2+nu3
    cbind(nu1/de, nu2/de, nu3/de)
}
dp1=Deriv(funLog, x=c(x=1, x=2))

Best,
Serguei.

Genwei007 has written at  Sun, 21 Feb 2016 00:42:45 -0800

**Comment by sgsokol** [comment]
Le 21/02/2016 06:37, genwei007 a écrit :

> Hi Serguei,
> 
> Apologize to bother again! What if |Theta| is vector?
> 
> |funLog <- function(x,Theta,ncat){ nu <- cbind(1, exp(Theta - x[1] ), exp(2*(Theta) - (x[1]+x[2]) ) ) de = nu[,1] + nu[,2] + nu[,3] p1 = nu[,1]/de p2 = 
> nu[,2]/de p3 = nu[,3]/de log(cbind(p1,p2,p3)) } dp1 = Deriv(funLog,c(x=1,x=2)) |
> 
> BTW, |for (){}| and |rowSums| seems not working in Deriv for now. Does it mean I have to make formula as explicitly as possible, right?
> 
> Could you give an example of what you expect when differentiating rowSums() ?

Best,
Serguei.

**Comment by cwliu007** [comment]
Hi Serguei,

At initial, I hope to run

```
fun <- function(x,Theta,ncat){
    nu <- matrix(1,nrow(Theta),ncat)
    for (k in 2:ncat){
        nu[,k] <- exp(k*Theta-sum(x[1:(k-1)]))
    }
    de <- rowSums(nu)
    nu/ kronecker(matrix(1,1,ncat), de)
} 
fun(c(0,1),matrix(-4:4),3)

dp1=Deriv(fun, x=c(x=1, x=2))
```

But I think Deriv cannot predict the length of Theta after compilation as you mentioned.

**Comment by cwliu007** [comment]
Hi Serguei,

YES! Your method works well to this case. Thank you so much:)
