### ISSUE TITLE
Issues in Simplify.log

### ISSUE THREAD

**Issue by notEvil** [sgsokol/Deriv#9]
Hi,

I found that two simplifications for `log` are obviously incorrect. `log(a/b) = log(a) - log(b)` and `log(a*b) = log(a) + log(b)` only for positive `a` and `b`. If both are negative, this simplification introduces `NA`.
Should be easy to fix (remove) ;)

Best regards, !evil

**Comment by sgsokol** [comment]
Instead of simple remove, I think about `log(a/b)=log(abs(a))-log(abs(b))` and the same tric for `a*b`. Would it fit your situation?

**Comment by notEvil** [comment]
This fix would assume that the sign of `a` and `b` are always equal ;)
For now I removed the code and it seems to work fine. In any case, I don't really see the 'simplification'. `log(a/b)` seems to be a little faster than `log(a) - log(b)` anyway  (just did a simple microbenchmark).

**Comment by sgsokol** [comment]
Indeed, it must be equal. Otherwise, the log() is meaningless.
The simplification is symbolical, not numerical so no matter what is faster. May be `log(a)` will simplify with another term and it cannot happen if we keep `log(a/b)` or `log(a*b)` as is.

**Comment by notEvil** [comment]
I see. If you choose to use `log(a*/b)=log(abs(a))+-log(abs(b))` then obviously the argument space for the derivative is expanded. You should state somewhere that this can happen.

**Comment by sgsokol** [comment]
Well,
Finally, I left the code as is. You are right when you are saying that introducing abs() is too intrusive. Even if it would be written somewhere in the doc, it would be far from naturally expecting behaviour.
If some similar complaints appear in the future, I will introduce an option for disabling simplifications.

**Comment by notEvil** [comment]
This is rather unsatisfactory imho. The simplification obviously doesn't work when both variables are negative. This means that `Simplify` kills valid expressions. Please drop this simplification for the sake of validity.
